-- CreateTable
CREATE TABLE "Item" (
    "id" SERIAL NOT NULL,
    "classificationId" INTEGER NOT NULL,
    "categoryId" INTEGER NOT NULL,
    "groupId" INTEGER NOT NULL,
    "subGroupId" INTEGER,
    "itemName" TEXT NOT NULL,
    "description" TEXT,
    "grade" TEXT,
    "partDescription" TEXT,
    "unitId" INTEGER NOT NULL,
    "purchaseRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "sellingRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "hsnId" INTEGER NOT NULL,
    "gstSlab" INTEGER NOT NULL,
    "drawingNo" TEXT,
    "drawingRevision" TEXT,
    "customerItemCode" TEXT,
    "allowedExcessQty" DOUBLE PRECISION,
    "thickness" DOUBLE PRECISION,
    "length" DOUBLE PRECISION,
    "width" DOUBLE PRECISION,
    "netWeight" DOUBLE PRECISION,
    "grossWeight" DOUBLE PRECISION,
    "weightUomId" INTEGER,
    "density" DOUBLE PRECISION,
    "densityUomId" INTEGER,
    "surfaceArea" DOUBLE PRECISION,
    "surfaceAreaUomId" INTEGER,
    "rawMaterialItemId" INTEGER,
    "scrapItemId" INTEGER,
    "leadTimeDays" INTEGER,
    "minStockQty" DOUBLE PRECISION,
    "minOrderQty" DOUBLE PRECISION,
    "valuationMethod" TEXT,
    "allowNegativeStock" BOOLEAN NOT NULL DEFAULT false,
    "inspectionRequired" BOOLEAN NOT NULL DEFAULT false,
    "isDimensional" BOOLEAN NOT NULL DEFAULT false,
    "isScrap" BOOLEAN NOT NULL DEFAULT false,
    "itemType" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Item_pkey" PRIMARY KEY ("id")
);
