const router = require('express').Router();

const roles = require('./roles.route');
const menus = require('./menus.route');
const region = require('./region.route');
const zone = require('./zone.route');
const subZone = require('./sub_zone.route');
const department = require('./department.route');
const common = require('./state_country.route');
const plantUnit = require('./plant_unit.route');
const warehouses = require('./warehouses.route');
const partyGroups = require('./party_groups.route');
const bankAccounts = require('./bank_accounts.route');
const paymentTerms = require('./payment_terms.route');
const companyDetails = require('./company_details.route');
const users = require('./users.route');
const supplier = require('./supplier.route');
const customer = require('./customer.route');
const hsn = require('./hsn.route');
const classification = require('./classification.route');
const category = require('./category.route');
const group = require('./group.route');
const subGroup = require('./sub_group.route');
const rawMaterial = require('./raw_material.route');
const item = require('./item.route');
const lead = require('./lead.route');
const quotation = require('./quotation.route');
const salesOrder = require('./sales_order.route');
const taxInvoice = require('./tax_invoice.route');
const purchaseIndent = require('./purchase_indent.route');

router.use('/roles', roles);
router.use('/menus', menus);
router.use('/region', region);
router.use('/zone', zone);
router.use('/sub-zone', subZone);
router.use('/department', department);
router.use('/common', common);
router.use('/plant-unit', plantUnit);
router.use('/warehouses', warehouses);
router.use('/party-group', partyGroups);
router.use('/bank-accounts', bankAccounts);
router.use('/payment-terms', paymentTerms);
router.use('/company-details', companyDetails);
router.use('/users', users);
router.use('/suppliers', supplier);
router.use('/customers', customer);
router.use('/hsn', hsn);
router.use('/classification', classification);
router.use('/category', category);
router.use('/group', group);
router.use('/sub-group', subGroup);
router.use('/raw-material', rawMaterial);
router.use('/item', item);
router.use('/lead', lead);
router.use('/quotation', quotation);
router.use('/sales-order', salesOrder);
router.use('/tax-invoice', taxInvoice);
router.use('/purchase-indent', purchaseIndent);

module.exports = router;